name: 'Comment'
description: 'Post comment to pull request'
inputs:
  github-token:
    description: 'The token to authenticate with'
  message:
    description: 'Message to post'
    required: false
    default: 'none'
  note:
    description: 'Note comment used to find the comment for updating'
    required: false
  reaction:
    description: 'Reaction to check by the PR author'
    required: false
outputs:
  found_reaction:
    description: 'Found reaction in comment'
    value: ${{ steps.run-python.outputs.found_reaction }}
runs:
  using: "composite"
  steps:
    - id: setup-python
      run: |
        pip3 install setuptools wheel pygithub
      shell: bash
    - id: run-python
      run: |
           python3 ${{ github.action_path }}/action.py -n "${{ inputs.note }}" \
           -m "${{ inputs.message }}" -r "${{ inputs.reaction }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
