name: 'Contributions'
description: 'Manage nrfconnect contributions'
inputs:
  github-token:
    description: 'The token to authenticate with'
  command:
    description: 'Command to execute'
    required: true
  message:
    description: 'Message to post'
    required: false
    default: 'none'
  labels:
    description: 'Comma-separated list of labels'
    required: false
    default: 'none'

runs:
  using: "composite"
  steps: 
    - run: echo "Action Start ${{ inputs.input-str }}"
      shell: bash
    - id: setup-python
      run: |
        pip3 install setuptools wheel
        pip3 install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - id: run-python
      run: |
           python3 ${{ github.action_path }}/action.py -c "${{ inputs.command }}" \
           -m "${{ inputs.message }}" -l "${{ inputs.labels }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
